# Generated by Django 3.1.2 on 2020-10-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_auto_20201027_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=1000, null=True, verbose_name='项目名称')),
                ('project_remark', models.CharField(max_length=1000, null=True, verbose_name='项目备注')),
                ('project_build_user', models.CharField(max_length=256, null=True, verbose_name='项目创建者名称')),
                ('project_build_other_user', models.CharField(max_length=256, null=True, verbose_name='项目其他创建者的名称')),
            ],
        ),
    ]
